#!/usr/bin/env node
// Regenerate the Cognia-format artifacts (plugin.json + dist/index.js) inside each
// plugin directory, using the canonical converter — the same module the managed
// `cognia` CLI embeds for `cognia plugin import` (lib/plugin/convert →
// crates/cognia-cli/assets/plugin-convert.cjs). Nothing is hand-authored; the
// committed artifacts are checked in so a Cognia host can build-free install the
// plugin directory directly (plugin_install / plugin_install_from_github --subdir).
//
// Converter discovery order:
//   1. --convert <path>            explicit path to a plugin-convert.{cjs,mjs} bundle
//   2. FIXER_COGNIA_CONVERT        same, via env
//   3. `cognia` on PATH            managed CLI (Plugins → DevTools → cognia CLI)
//
// Usage:
//   node scripts/build-cognia.mjs                 regenerate all plugins
//   node scripts/build-cognia.mjs --plugin <id>   one plugin
//   node scripts/build-cognia.mjs --check         fail if committed artifacts drift
import { execFileSync } from 'node:child_process'
import { cpSync, existsSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { basename, dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const pluginsDir = join(repoRoot, 'plugins')

export const STAGING_EXCLUDES = new Set([
  '.codex-plugin', // ambiguous for ecosystem detection; Claude is the import source
  'plugin.json',   // a root manifest would flip detection to "cognia"
  'dist',          // regenerated
  'node_modules',
])

/**
 * Command skills convert to `inline` skills named after the command. When a real
 * bundle skill already owns the same id (e.g. /branch-sync vs the branch-sync
 * skill), the thin delegating shim would shadow the real skill — Cognia's skill
 * registry is last-wins within one plugin. Drop the inline duplicate and keep
 * the bundle, which already carries the trigger phrases.
 */
export const dedupeSkills = (skills) => {
  const bundleIds = new Set(
    skills.filter((skill) => skill.source?.kind !== 'inline').map((skill) => skill.id)
  )
  return skills.filter(
    (skill) => skill.source?.kind !== 'inline' || !bundleIds.has(skill.id)
  )
}

export const distEntry = (manifest) => `"use strict";
// Cognia runtime entry — generated by scripts/build-cognia.mjs.
// \`manifest\` must stay identical to plugin.json (the host enforces manifest
// parity against the module-exported definition). Regenerate, don't hand-edit.
const manifest = ${JSON.stringify(manifest, null, 2)};

const definition = {
  manifest,
  activate: async (ctx) => {
    ctx.logger.info(${JSON.stringify(manifest.id + ' activated')});
  },
  deactivate: async (ctx) => {
    ctx?.logger.info(${JSON.stringify(manifest.id + ' deactivated')});
  },
};

module.exports = { __esModule: true, default: definition };
`

const parseArgs = (argv) => {
  const out = { check: false, plugin: null, convert: null }
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i]
    if (arg === '--check') out.check = true
    else if (arg === '--plugin') out.plugin = argv[++i]
    else if (arg === '--convert') out.convert = argv[++i]
    else throw new Error(`unknown option: ${arg}`)
  }
  return out
}

const onPath = (bin) => {
  try {
    execFileSync(bin, ['--version'], { stdio: ['ignore', 'pipe', 'ignore'] })
    return true
  } catch {
    return false
  }
}

/** Convert one staged Claude-format plugin dir into <outDir>. Returns the out dir. */
const convert = (converter, stagedDir, outDir) => {
  const args = ['--operation', 'import', '--from', 'plugin', '--input', stagedDir, '--to', 'cognia', '--dir', outDir]
  let raw
  if (converter.kind === 'bundle') {
    raw = execFileSync(process.execPath, [converter.path, ...args], { encoding: 'utf8' })
  } else {
    raw = execFileSync('cognia', ['plugin', 'import', ...args, '--json'], { encoding: 'utf8' })
  }
  const result = JSON.parse(raw)
  if (!result.ok) {
    const blocking = result.report?.blocking?.map((b) => `  - ${b.path}: ${b.message}`).join('\n')
    throw new Error(`cognia conversion failed: ${result.error || 'unknown'}${blocking ? `\n${blocking}` : ''}`)
  }
  return outDir
}

const resolveConverter = (flag) => {
  const path = flag || process.env.FIXER_COGNIA_CONVERT
  if (path) {
    if (!existsSync(path)) throw new Error(`converter not found: ${path}`)
    return { kind: 'bundle', path: resolve(path) }
  }
  if (onPath('cognia')) return { kind: 'cli' }
  throw new Error(
    'no Cognia converter available. Install the managed `cognia` CLI ' +
    '(Plugins → DevTools → cognia CLI) or point FIXER_COGNIA_CONVERT / --convert ' +
    'at a plugin-convert.{cjs,mjs} bundle (the asset the managed CLI embeds).'
  )
}

const stage = (pluginRoot, stagingParent) => {
  const staged = join(stagingParent, basename(pluginRoot))
  cpSync(pluginRoot, staged, {
    recursive: true,
    filter: (source) => {
      const rel = source.slice(pluginRoot.length).replaceAll('\\', '/').replace(/^\//, '')
      const top = rel.split('/')[0]
      return !STAGING_EXCLUDES.has(top)
    },
  })
  return staged
}

const listPlugins = (only) => {
  const entries = []
  for (const name of readdirSync(pluginsDir, { withFileTypes: true })) {
    if (!name.isDirectory()) continue
    if (only && name.name !== only) continue
    if (existsSync(join(pluginsDir, name.name, '.claude-plugin', 'plugin.json'))) {
      entries.push(join(pluginsDir, name.name))
    }
  }
  if (only && !entries.length) throw new Error(`no plugin named ${only} under plugins/`)
  return entries
}

const buildOne = (converter, pluginRoot, workspace, check) => {
  const staged = stage(pluginRoot, join(workspace, 'staged'))
  const outDir = join(workspace, `out-${basename(pluginRoot)}`)
  convert(converter, staged, outDir)
  const manifest = JSON.parse(readFileSync(join(outDir, 'plugin.json'), 'utf8'))
  const before = manifest.skills?.length ?? 0
  if (manifest.skills) manifest.skills = dedupeSkills(manifest.skills)
  const dropped = before - (manifest.skills?.length ?? 0)
  return { manifest, dropped }
}

const writeArtifacts = (pluginRoot, manifest) => {
  writeFileSync(join(pluginRoot, 'plugin.json'), JSON.stringify(manifest, null, 2) + '\n')
  const dist = join(pluginRoot, 'dist')
  mkdirSync(dist, { recursive: true })
  writeFileSync(join(dist, 'index.js'), distEntry(manifest))
}

const checkArtifacts = (pluginRoot, manifest) => {
  const committedManifest = JSON.parse(readFileSync(join(pluginRoot, 'plugin.json'), 'utf8'))
  const committedEntry = readFileSync(join(pluginRoot, 'dist', 'index.js'), 'utf8')
  const diffs = []
  if (JSON.stringify(committedManifest) !== JSON.stringify(manifest)) diffs.push('plugin.json')
  if (committedEntry !== distEntry(manifest)) diffs.push('dist/index.js')
  return diffs
}

const main = () => {
  const args = parseArgs(process.argv.slice(2))
  const converter = resolveConverter(args.convert)
  const workspace = mkdtempSync(join(tmpdir(), 'issue-fixer-cognia-'))
  let failed = false
  try {
    for (const pluginRoot of listPlugins(args.plugin)) {
      const id = basename(pluginRoot)
      const { manifest, dropped } = buildOne(converter, pluginRoot, workspace, args.check)
      if (args.check) {
        const diffs = checkArtifacts(pluginRoot, manifest)
        if (diffs.length) {
          failed = true
          console.error(`${id}: cognia artifacts stale — ${diffs.join(', ')}. Re-run pnpm build:cognia`)
        } else {
          console.log(`${id}: cognia artifacts in sync`)
        }
      } else {
        writeArtifacts(pluginRoot, manifest)
        console.log(
          `${id}: wrote plugin.json + dist/index.js ` +
          `(${manifest.skills?.length ?? 0} skills, ${Object.keys(manifest.commandHooks ?? {}).length} hook events` +
          (dropped ? `, dropped ${dropped} shadowing command-skill(s)` : '') + ')'
        )
      }
    }
  } finally {
    rmSync(workspace, { recursive: true, force: true })
  }
  if (failed) process.exitCode = 1
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main()
}
